services:
  _defaults:
    autowire: true
    public: false

  PrestaShop\PrestaShop\Adapter\Discount\CommandHandler\AddDiscountHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Discount\CommandHandler\DeleteDiscountHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Discount\CommandHandler\UpdateDiscountHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Discount\Update\Filler\DiscountFiller:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Discount\QueryHandler\GetDiscountForEditingHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Discount\Validate\DiscountValidator:

  PrestaShop\PrestaShop\Adapter\Discount\Repository\DiscountRepository:
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
