version: '3.6'
services:
  node:
    image: node:20
    container_name: ddev-${DDEV_PROJECT}-node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install && npm run dev"